main:
  push:
    - services:
        - name: docker
          options:
            rootlessBuildkitd:
              enabled: true
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}"
          exports:
            info: IMAGE_REPO

        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: docker build and push
          script: |
            docker buildx build \
              -t $IMAGE_REPO:${CNB_COMMIT_SHORT} \
              -t $IMAGE_REPO:latest \
              --platform linux/amd64,linux/arm64 \
              --cache-to type=registry,ref=$IMAGE_REPO:buildcache,mode=max \
              --cache-from type=registry,ref=$IMAGE_REPO:buildcache \
              --push .
