main:
  push:
    - imports: https://cnb.cool/rich/tool-group/cnb-secret/-/blob/main/github/secret.yml
      services:
        - docker
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Jesn/mcp-tools-debugger.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_email: ${GIT_EMAIL}
            git_user: ${GIT_USER}

    - services:
        - name: docker
          options:
            rootlessBuildkitd:
              enabled: true
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}"
          exports:
            info: IMAGE_REPO

        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}

        - name: docker build and push
          script: |
            docker buildx build \
              -t $IMAGE_REPO:${CNB_COMMIT_SHORT} \
              -t $IMAGE_REPO:latest \
              --platform linux/amd64,linux/arm64 \
              --cache-to type=registry,ref=$IMAGE_REPO:buildcache,mode=max \
              --cache-from type=registry,ref=$IMAGE_REPO:buildcache \
              --push .
